# Experiment  9: Study of Pandas

### Name: Lehalyaa L
### PRN: 25070123176
### Batch: ENTC - A2

In [2]:
# Initialisation of Pandas

import pandas as pd

s = pd.Series([1, 3, 5, 6, 8])
s

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [19]:
# Create a Dataframe

data = {
    "Name" : ["Lehalyaa", "Aditi Mishra", "Gayatri", "Arjit", "Bedang"],
    "Marks" : [87, 100, 95, 96, 83]
}
df = pd.DataFrame(data)
df

           Name  Marks
0      Lehalyaa     87
1  Aditi Mishra    100
2       Gayatri     95
3         Arjit     96
4        Bedang     83

In [20]:
''' if nothing is mentioned in the bracet then first and last five is printed
for head and tail function. Nut, the number of rows to be printed can be changed'''

df.head(2)

           Name  Marks
0      Lehalyaa     87
1  Aditi Mishra    100

In [21]:
df.tail(3)

      Name  Marks
2  Gayatri     95
3    Arjit     96
4   Bedang     83

In [22]:
# Find the structure of the dataframe

df.shape

(5, 2)

In [23]:
# To check the number of columns

df.ndim

2

In [24]:
# Total number of elements = no of columns x no of rows

df.size

10

In [35]:
# Display column Names

df.columns

Index(['Name', 'Marks', 'Grade'], dtype='object')

In [34]:
# Check Data Types of each Column

df.dtypes
''' object   -   Categorical data
    int64    -   Numerical Data'''

' object   -   Categorical data\n    int64    -   Numerical Data'

In [33]:
# Access Individual Column

df["Name"]

0        Lehalyaa
1    Aditi Mishra
2         Gayatri
3           Arjit
4          Bedang
Name: Name, dtype: object

In [32]:
# Access Specific Row

df.loc[1]

Name     Aditi Mishra
Marks             100
Grade     Distinction
Name: 1, dtype: object

In [43]:
# Add a New Column

df["Grade"] = ["Second Class", "Distinction", "First Class", "First Class", "Third Class"]

df

           Name  Marks         Grade
0      Lehalyaa     89  Second Class
1  Aditi Mishra    100   Distinction
2       Gayatri     95   First Class
3         Arjit     96   First Class
4        Bedang     83   Third Class

In [40]:
# Update Data in DataFrame
# Change marks of first student to 89

df.loc[0, "Marks"] = 89
df

           Name  Marks         Grade
0      Lehalyaa     89  Second Class
1  Aditi Mishra    100   Distinction
2       Gayatri     95   First Class
3         Arjit     96   First Class
4        Bedang     83   Third Class

In [44]:
# Delete a Column

df.drop("Grade", axis=1, inplace = True)
''' axis = 1 --> column, axis = 0 --> row '''
''' inplace is used to make the changes permanently to the dataframe'''
df

           Name  Marks
0      Lehalyaa     89
1  Aditi Mishra    100
2       Gayatri     95
3         Arjit     96
4        Bedang     83

In [45]:
# Perform Basic Statistical Analysis

mean1 = df["Marks"].mean()
print("Mean: ", mean1)

Mean:  92.6

In [46]:
# Aggregate Functions in Data Frames

min_value = df["Marks"].min()
max_value = df["Marks"].max()
sum_value = df["Marks"].sum()

print("Minimum Value of Marks: ", min_value)
print("Maximum Value of Marks: ", max_value)
print("Sum of Marks: ", sum_value)

Minimum Value of Marks:  83
Maximum Value of Marks:  100
Sum of Marks:  463

In [48]:
# Apply conditions (Filtering)
# Display Students who scored more than 90

df[df["Marks"] > 90]

           Name  Marks
1  Aditi Mishra    100
2       Gayatri     95
3         Arjit     96